#------------------------------------
# Template
#------------------------------------
# 베이스 이미지를 명시합니다.
#FROM baseImage
## 추가로 필요한 파일들을 내려 받습니다.
#RUN command
## 컨테이너 시작 시 실행할 명령어를 명시합니다.
#CMD [ "executable" ]
##------------------------------------

# 베이스 이미지를 명시합니다.
FROM node:alpine

# 작업경로 설정
WORKDIR /usr/src/app

# 패키지 파일 복사
COPY package.json ./

# 추가로 필요한 파일들을 내려 받습니다.
RUN npm install

# 전체 파일 복사
COPY ./ ./

# 컨테이너 시작 시 실행할 명령어를 명시합니다.
CMD [ "npm", "run", "start" ]

